const val rootName = "SnapiBalancer"
const val rootGroup = "ru.snapix"
const val rootVersion = "1.3"

const val kotlinVersion = "2.0.0"
const val kotlinSerializationVersion = "1.6.3"
const val shadowJarVersion = "7.1.2"
const val velocityVersion = "3.2.0-SNAPSHOT"
const val protocolizeVersion = "2.3.3"
const val snapiLibraryVersion = "1.2"
